{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"ExceptionsHandler","level":"error","message":"Work order not found","stack":["Error: Work order not found\n    at WorkOrdersController.findOne (C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\src\\work-orders\\work-orders.controller.ts:35:13)\n    at async C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\node_modules\\@nestjs\\core\\router\\router-execution-context.js:46:28\n    at async C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\node_modules\\@nestjs\\core\\router\\router-proxy.js:9:17"]}
{"context":"ExceptionsHandler","level":"error","message":"Work order not found","stack":["Error: Work order not found\n    at WorkOrdersController.findOne (C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\src\\work-orders\\work-orders.controller.ts:35:13)\n    at async C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\node_modules\\@nestjs\\core\\router\\router-execution-context.js:46:28\n    at async C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\node_modules\\@nestjs\\core\\router\\router-proxy.js:9:17"]}
{"context":"ExceptionsHandler","level":"error","message":"Work order not found","stack":["Error: Work order not found\n    at WorkOrdersController.findOne (C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\src\\work-orders\\work-orders.controller.ts:35:13)\n    at async C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\node_modules\\@nestjs\\core\\router\\router-execution-context.js:46:28\n    at async C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\node_modules\\@nestjs\\core\\router\\router-proxy.js:9:17"]}
{"context":"ExceptionsHandler","level":"error","message":"Work order not found","stack":["Error: Work order not found\n    at WorkOrdersController.findOne (C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\src\\work-orders\\work-orders.controller.ts:35:13)\n    at async C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\node_modules\\@nestjs\\core\\router\\router-execution-context.js:46:28\n    at async C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\node_modules\\@nestjs\\core\\router\\router-proxy.js:9:17"]}
{"context":"ExceptionsHandler","level":"error","message":"Work order not found","stack":["Error: Work order not found\n    at WorkOrdersController.findOne (C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\src\\work-orders\\work-orders.controller.ts:35:13)\n    at async C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\node_modules\\@nestjs\\core\\router\\router-execution-context.js:46:28\n    at async C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\node_modules\\@nestjs\\core\\router\\router-proxy.js:9:17"]}
{"context":"ExceptionsHandler","level":"error","message":"Work order not found","stack":["Error: Work order not found\n    at WorkOrdersController.findOne (C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\src\\work-orders\\work-orders.controller.ts:35:13)\n    at async C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\node_modules\\@nestjs\\core\\router\\router-execution-context.js:46:28\n    at async C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\node_modules\\@nestjs\\core\\router\\router-proxy.js:9:17"]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"ExceptionsHandler","level":"error","message":"Work order not found","stack":["Error: Work order not found\n    at WorkOrdersController.findOne (C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\dist\\work-orders\\work-orders.controller.js:31:19)\n    at async C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\node_modules\\@nestjs\\core\\router\\router-execution-context.js:46:28\n    at async C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\node_modules\\@nestjs\\core\\router\\router-proxy.js:9:17"]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"ExceptionsHandler","level":"error","message":"Work order not found","stack":["Error: Work order not found\n    at WorkOrdersController.findOne (C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\dist\\work-orders\\work-orders.controller.js:31:19)\n    at async C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\node_modules\\@nestjs\\core\\router\\router-execution-context.js:46:28\n    at async C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\node_modules\\@nestjs\\core\\router\\router-proxy.js:9:17"]}
{"context":"ExceptionsHandler","level":"error","message":"Work order not found","stack":["Error: Work order not found\n    at WorkOrdersController.findOne (C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\dist\\work-orders\\work-orders.controller.js:31:19)\n    at async C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\node_modules\\@nestjs\\core\\router\\router-execution-context.js:46:28\n    at async C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\node_modules\\@nestjs\\core\\router\\router-proxy.js:9:17"]}
{"context":"ExceptionsHandler","level":"error","message":"Work order not found","stack":["Error: Work order not found\n    at WorkOrdersController.findOne (C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\dist\\work-orders\\work-orders.controller.js:31:19)\n    at async C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\node_modules\\@nestjs\\core\\router\\router-execution-context.js:46:28\n    at async C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\node_modules\\@nestjs\\core\\router\\router-proxy.js:9:17"]}
{"context":"ExceptionsHandler","level":"error","message":"Work order not found","stack":["Error: Work order not found\n    at WorkOrdersController.findOne (C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\dist\\work-orders\\work-orders.controller.js:31:19)\n    at async C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\node_modules\\@nestjs\\core\\router\\router-execution-context.js:46:28\n    at async C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\node_modules\\@nestjs\\core\\router\\router-proxy.js:9:17"]}
{"context":"ExceptionsHandler","level":"error","message":"Work order not found","stack":["Error: Work order not found\n    at WorkOrdersController.findOne (C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\dist\\work-orders\\work-orders.controller.js:31:19)\n    at async C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\node_modules\\@nestjs\\core\\router\\router-execution-context.js:46:28\n    at async C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\node_modules\\@nestjs\\core\\router\\router-proxy.js:9:17"]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"ExceptionsHandler","level":"error","message":"Work order not found","stack":["Error: Work order not found\n    at WorkOrdersController.findOne (C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\dist\\work-orders\\work-orders.controller.js:31:19)\n    at async C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\node_modules\\@nestjs\\core\\router\\router-execution-context.js:46:28\n    at async C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\node_modules\\@nestjs\\core\\router\\router-proxy.js:9:17"]}
{"context":"ExceptionsHandler","level":"error","message":"Work order not found","stack":["Error: Work order not found\n    at WorkOrdersController.findOne (C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\dist\\work-orders\\work-orders.controller.js:31:19)\n    at async C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\node_modules\\@nestjs\\core\\router\\router-execution-context.js:46:28\n    at async C:\\Users\\Cooper\\Documents\\Code\\WorkOrders\\apps\\backend\\node_modules\\@nestjs\\core\\router\\router-proxy.js:9:17"]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"PackageLoader","level":"error","message":"The \"class-validator\" package is missing. Please, make sure to install it to take advantage of ValidationPipe.","stack":[null]}
{"context":"PackageLoader","level":"error","message":"The \"class-validator\" package is missing. Please, make sure to install it to take advantage of ValidationPipe.","stack":[null]}
{"context":"PackageLoader","level":"error","message":"The \"class-validator\" package is missing. Please, make sure to install it to take advantage of ValidationPipe.","stack":[null]}
{"context":"ExceptionsHandler","level":"error","message":"Cannot query across one-to-many for property comments","stack":["Error: Cannot query across one-to-many for property comments\n    at UpdateQueryBuilder.createPropertyPath (C:\\Users\\Engineering\\Documents\\Cursor\\WOrMS\\WOrMS\\apps\\backend\\node_modules\\typeorm\\query-builder\\src\\query-builder\\QueryBuilder.ts:1418:27)\n    at UpdateQueryBuilder.createUpdateExpression (C:\\Users\\Engineering\\Documents\\Cursor\\WOrMS\\WOrMS\\apps\\backend\\node_modules\\typeorm\\query-builder\\src\\query-builder\\UpdateQueryBuilder.ts:493:18)\n    at UpdateQueryBuilder.getQuery (C:\\Users\\Engineering\\Documents\\Cursor\\WOrMS\\WOrMS\\apps\\backend\\node_modules\\typeorm\\query-builder\\src\\query-builder\\UpdateQueryBuilder.ts:53:21)\n    at UpdateQueryBuilder.getQueryAndParameters (C:\\Users\\Engineering\\Documents\\Cursor\\WOrMS\\WOrMS\\apps\\backend\\node_modules\\typeorm\\query-builder\\src\\query-builder\\QueryBuilder.ts:495:28)\n    at UpdateQueryBuilder.execute (C:\\Users\\Engineering\\Documents\\Cursor\\WOrMS\\WOrMS\\apps\\backend\\node_modules\\typeorm\\query-builder\\src\\query-builder\\UpdateQueryBuilder.ts:142:50)\n    at async WorkOrdersService.update (C:\\Users\\Engineering\\Documents\\Cursor\\WOrMS\\WOrMS\\apps\\backend\\src\\work-orders\\work-orders.service.ts:149:5)\n    at async C:\\Users\\Engineering\\Documents\\Cursor\\WOrMS\\WOrMS\\node_modules\\@nestjs\\core\\router\\router-execution-context.js:46:28\n    at async C:\\Users\\Engineering\\Documents\\Cursor\\WOrMS\\WOrMS\\node_modules\\@nestjs\\core\\router\\router-proxy.js:9:17"]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"ExceptionsHandler","level":"error","message":"Property \"customerName\" was not found in \"WorkOrder\". Make sure your query is correct.","stack":["EntityPropertyNotFoundError: Property \"customerName\" was not found in \"WorkOrder\". Make sure your query is correct.\n    at <anonymous> (C:\\Users\\Engineering\\Documents\\Cursor\\WOrMS\\WOrMS\\apps\\backend\\node_modules\\typeorm\\query-builder\\src\\query-builder\\UpdateQueryBuilder.ts:500:31)\n    at Array.forEach (<anonymous>)\n    at UpdateQueryBuilder.createUpdateExpression (C:\\Users\\Engineering\\Documents\\Cursor\\WOrMS\\WOrMS\\apps\\backend\\node_modules\\typeorm\\query-builder\\src\\query-builder\\UpdateQueryBuilder.ts:493:68)\n    at UpdateQueryBuilder.getQuery (C:\\Users\\Engineering\\Documents\\Cursor\\WOrMS\\WOrMS\\apps\\backend\\node_modules\\typeorm\\query-builder\\src\\query-builder\\UpdateQueryBuilder.ts:53:21)\n    at UpdateQueryBuilder.getQueryAndParameters (C:\\Users\\Engineering\\Documents\\Cursor\\WOrMS\\WOrMS\\apps\\backend\\node_modules\\typeorm\\query-builder\\src\\query-builder\\QueryBuilder.ts:495:28)\n    at UpdateQueryBuilder.execute (C:\\Users\\Engineering\\Documents\\Cursor\\WOrMS\\WOrMS\\apps\\backend\\node_modules\\typeorm\\query-builder\\src\\query-builder\\UpdateQueryBuilder.ts:142:50)\n    at async WorkOrdersService.update (C:\\Users\\Engineering\\Documents\\Cursor\\WOrMS\\WOrMS\\apps\\backend\\src\\work-orders\\work-orders.service.ts:144:5)\n    at async C:\\Users\\Engineering\\Documents\\Cursor\\WOrMS\\WOrMS\\node_modules\\@nestjs\\core\\router\\router-execution-context.js:46:28\n    at async C:\\Users\\Engineering\\Documents\\Cursor\\WOrMS\\WOrMS\\node_modules\\@nestjs\\core\\router\\router-proxy.js:9:17"]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"ExceptionsHandler","level":"error","message":"SQLITE_CONSTRAINT: NOT NULL constraint failed: work_orders.title","stack":["QueryFailedError: SQLITE_CONSTRAINT: NOT NULL constraint failed: work_orders.title\n    at Statement.handler (C:\\Users\\Engineering\\Documents\\Cursor\\WOrMS\\WOrMS\\apps\\backend\\node_modules\\typeorm\\driver\\src\\driver\\sqlite\\SqliteQueryRunner.ts:133:29)"]}
{"context":"ExceptionsHandler","level":"error","message":"SQLITE_CONSTRAINT: NOT NULL constraint failed: work_orders.title","stack":["QueryFailedError: SQLITE_CONSTRAINT: NOT NULL constraint failed: work_orders.title\n    at Statement.handler (C:\\Users\\Engineering\\Documents\\Cursor\\WOrMS\\WOrMS\\apps\\backend\\node_modules\\typeorm\\driver\\src\\driver\\sqlite\\SqliteQueryRunner.ts:133:29)"]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"ExceptionsHandler","level":"error","message":"SQLITE_CONSTRAINT: FOREIGN KEY constraint failed","stack":["QueryFailedError: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed\n    at Statement.handler (C:\\Users\\Engineering\\Documents\\Cursor\\WOrMS\\WOrMS\\apps\\backend\\node_modules\\typeorm\\driver\\src\\driver\\sqlite\\SqliteQueryRunner.ts:133:29)"]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"ExceptionsHandler","level":"error","message":"SQLITE_CONSTRAINT: FOREIGN KEY constraint failed","stack":["QueryFailedError: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed\n    at Statement.handler (C:\\Users\\Engineering\\Documents\\Cursor\\WOrMS\\WOrMS\\apps\\backend\\node_modules\\typeorm\\driver\\src\\driver\\sqlite\\SqliteQueryRunner.ts:133:29)"]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
{"context":"NestApplication","level":"error","message":"Error: listen EADDRINUSE: address already in use :::3001","stack":[null]}
